### ISSUE TITLE
Support dpop protocol to sender constrain access tokens.

### ISSUE THREAD

**Issue by damooo** [sebadob/rauthy#132]
Hello, thanks a lot for `rauthy`. It really fills important void.

This is request to add support for [RFC 9449 DPoP](https://datatracker.ietf.org/doc/html/rfc9449).

> OAuth 2.0 Demonstrating Proof of Possession (DPoP) is a mechanism for sender-constraining OAuth 2.0 tokens via a proof-of-possession mechanism on the application level. This mechanism allows for the detection of replay attacks with access and refresh tokens.

dpop is in development for many years, and proven to be defacto standard. Now it is also an official rfc. Keycloak also landed support for dpop recently. It also enables to have decentralized identities.

It would  be great to have the support in rauthy.

[Solid-OIDC](https://solidproject.org/TR/oidc) spec mandates dpop. I am also the maintainer of [`Manas`](https://github.com/manomayam/manas/) project that aims to create [Solid protocol](solidproject.org/) compliant servers. Storage part is done. solid-oidc compliant oidc provider is the next move to finally bring in complete solution. I am very hopeful on adapting rauthy for the purpose. Hope there can be collaboration.

Thanks again for great work.

**Comment by sebadob** [comment]
I had a very quick look into the RFC and it seems that it should not be that big of a deal.  
However, I need to read the full document in detail to make sure I don't forget something.

If you are working on a client implementation, it would actually be interesting to directly use it for testing purposes of the server side, so no one can overlook something.

**Comment by damooo** [comment]
Thanks for that _/\\\_.

I released a crate for [dpop](https://docs.rs/dpop/latest/dpop/proof/index.html). It doesn't have comprehensive tests though. It was used in dpop token verification at resource server (RS) in above project. Would be improving it for comprehensive support.

**Comment by sebadob** [comment]
The very first basics are there. They are currently still unused, but I will implement the whole feature over a few smaller PR's.

In the beginning, I will only support `ed25519` keys, because after a lot of debugging, I found out, that my IDE has a serious internal problem when trying resolve the internal types of the `rsa` crate. An issue about this already exists and will hopefully be solved soon. Until then, working with this kind of code is almost impossible, if I would not switch to another IDE.

This first step makes it possible to extract the `DPoP` header from an incoming request, deserialize it into the format from the RFC and do the first found of validation.

The next PR's will actually cary about looking for this Header and then finally implementing it into the tokens.

**Comment by sebadob** [comment]
I merged the 2nd PR, which should make it work.

I have done the implementation myself from scratch, which I usually like to do to really understand things in detail.  
There are some minor open questions and code is not optimized yet, but I created a nightly container image with these additions.

It would be nice, if you could do some tests on your side, since I have never worked with DPoP so far and I don't have any applications for real world testing, that actually use it right now.

I need to dig a big deeper into the `nonce` feature, if it is actually needed at all by Rauthy and if yes, what I need to do about it. The `ath` claim, if I got it correctly so far, is not important on Rauthy's side as well, since it actually creates the access token at first.
I have some unit tests for the validation and fingerprinting and the first simple integration test incl. refresh token.

Anyway, I will leave this issue open for now, until you have done some testing. The container image is the SQLite version of Rauthy:

`docker run -p 8080:8080 ghcr.io/sebadob/rauthy:0.17.1-20231102-lite`

**Comment by damooo** [comment]
Thanks alot @sebadob _/\\\_. I should test it and revert back.

**Comment by damooo** [comment]
Sorry for my language .  I meant to respond back here with feedback.

**Comment by damooo** [comment]
Great work @sebadob _/\\\_.

Following are few observations.

1. `DPOP_TOKEN_ENDPOINT` is computed with hardcoded `https` scheme. Thus it makes `htu` claim mismatch when served with `http`. probably `LISTEN_SCHEME` have to be used. https://github.com/sebadob/rauthy/blob/a24a257b505742aeb4a2e6a13d2f6d421ba08c60/rauthy-common/src/constants.rs#L93-L97
2. It would be suggestive to return `www-authenticate` header with `error=invalid_dpop_proof` to pinpoint dpop proof error as recommonded in spec.
3. dpop specifies an extension for [Client registration metadata](https://datatracker.ietf.org/doc/html/rfc9449#section-5.2), that requires to mandate dpop, if `dpop_bound_access_tokens` is true.
4. On an orthogonal note, oidc token endpoint's utoipa swagger metadata should specify data content-type to be `application/x-www-form-urlencoded` for `post_token` fn. It defaults to json. https://github.com/sebadob/rauthy/blob/a24a257b505742aeb4a2e6a13d2f6d421ba08c60/rauthy-handlers/src/oidc.rs#L505 .
5. For the same swagger endpoint, it would be great to have utoipa [`SecurityEndpoint`](https://docs.rs/utoipa/latest/utoipa/openapi/security/struct.SecurityRequirement.html) defined to allow specifying `DPoP` header in swagger in future.

> I found out, that my IDE has a serious internal problem when trying resolve the internal types of the rsa crate.

Is there anything we can possibly do about it? `RSA` keys are ubiquitous in the ecosystem currently. Most apps only using them. It may be useful to have an abstraction layer over pub-keys to abstract away key alg. I used `picky` crate for pubkeys and jwts in above crate.

> I need to dig a bit deeper into the nonce feature, if it is actually needed at all by Rauthy and if yes, what I need to do about it.

Though nonce is not required, it is highly recommended, as it completes the  possession proof squarely. As spec mentions: `When server-provided nonces are used, possession of the proof-of-possession key is being demonstrated -- not just possession of a DPoP proof.` 

I.e. if a malicious actor got control of an app for small time, then he can mint dpop-proofs for arbitrary future and steal them to use later. If nonce is mandated, server can regularly switch active nonce globally in a time window (say 10 mins), and clients must mint and provide dpop-proofs with current active nonce. This finally mitigates such stealing attacks. It may be more significant for refresh token endpoint.

> The ath claim, if I got it correctly so far, is not important on Rauthy's side as well, since it actually creates the access token at first.

Yes. It is only meaningful for resource servers.

-------------------

I saw that currently client dynamic registration is not supported. Can i open an issue for future?

I would be creating a cimplete rust client for oidc with dpop and webid, that maybe useful for comprehensive testing. As existing apps are too coupled with mode of registration, pub key alg, webid,etc.

Though i want to create PR for some of above, currently my laptop is kindof dysfunct for few days _/\\\_.

**Comment by sebadob** [comment]
Thanks for your feedback.

1. Yes the endpoint is hardcoded with HTTPS, since it should never be used without TLS, but I agree that this is cumbersome when doing local dev. I will fix that and allow HTTP if `DEV_MODE=true` in the config.

2. Will adjust that. The code is not complete and by no means pretty yet.

3. That is something that was unclear to me. If I got the RFC right, this should be set if the given client always forces DPoP and would not allow anything else. But Rauthy does not do this (yet). The behavior for now is, that when you provide the `DPoP` header during POST /token, you will get a DPoP token and a Bearer otherwise. This means by RFC I should not set this, if I am right:

 dpop_bound_access_tokens:
    A boolean value specifying whether the client always uses DPoP for token requests. **If omitted, the default value is false.**

4. I will have a look how I can specify this with utoipa. When I added all these utoipa documentation links, I was not able to do this back then (I am working for a long time on Rauthy already as a side project).
Additionally, you cannot use Swagger for now to test the Backend, at least for most of the endpoints. Rauthy's API is pretty locked down and very strict up to a point where Swagger cannot handle this authentication (I think).

5. About the nonce, I need to dig a bit deeper into this, as I mentioned in my earlier post.


The dynamic client registration will come afterwards, when DPoP is working properly, but yes sure you can open an issue about it. I have just a lot of other stuff on the table at the moment.

**Comment by damooo** [comment]
> That is something that was unclear to me. If I got the RFC right, this should be set if the given client always forces DPoP and would not allow anything else.

Yes indeed. The request was to for having a field at client registration time, and interpretating that.

I mentioned about dynamic registration only bcz, most of  existing clients like SolidOs are using that approach _/\\\_. Sorry for such insistence.

**Comment by sebadob** [comment]
No worries. :) 
I still have that on the TODO.

**Comment by sebadob** [comment]
So, `nonce`s should be working now.
This was a rabbit hole way deeper than I thought.

Since I want to release a new version because of the License change, I will include the PR's with the new release.
DPoP support will be marked experimental for that one.

If would be nice, if you could do tests again with the v0.18.0 which then comes in the next 2 hours.
When the DPoP feature is fully working and complete, we can do dynamic client registration in another issue.

**Comment by damooo** [comment]
Sorry for late response. The existing clients are little adhoc with coupling and assumptions. Hence testing becomes very manual computation. Though, so far looks great to me.

I am hence will be developing a client and a test crate for end-to-end automated tests of `Rauthy` oidc flows, using headless chromium. I should soon provide updates regarding that.

Thanks again.

**Comment by sebadob** [comment]
That sounds great.

Yes it is a bit difficult to do on Rauthy's side as well. Most of the current JWT related crated just cannot do this stuff. For instance, I am using `jwt-simple` for token generation, which is a really good crate to do this, since it prevents at lot of common errors you could make with JWTs. The problem is, it cannot do DPoP tokens
There are some that could make it work, but these are a bit annoying when compiling to musl, which I do with Rauthy.

So the current DPoP token validation is fully manual. That's why the RSA verification is not just automatically there, but it will come.

One thing I will add next to "complete" the DPoP feature is the `jkt` claim durint the auth code request. When this is added, Rauthy can then send the `DPoP-nonce` header with the very first response to the callback URL. This makes the whole process a bit more efficient in the end, since a client can never get back an HTTP 400 because Rauthy has maybe rotated the DPoP nonce in the meantime.

Anyway, the issue itself can be closed with all of the current stuff working, right?
`jkt` claim and RSA tokens will come anyway in the near future.

**Comment by damooo** [comment]
Yes. I will be closing the issue.

Above mentioned `dpop` crate has comprehensive support  for dpop jwts btw. And it builts upon base jwt support from `picky` crate that supports pki infra, httpsig, jws, jwt, jwe etc in a single crate. It was chosen as base bcz, solid also has direct authn requirements using webid-tls, httpsig, etc.

**Comment by sebadob** [comment]
I am trying to not pull in more dependencies into Rauthy because a full release pipeline takes ~45 minutes currently, but I will take a look at it and see if it makes a big difference (and can be compiled to musl nicely).

Thank you

**Comment by sebadob** [comment]
It is not officially released yet, but in the latest nightly build, RSA support for DPoP tokens is working:

`ghcr.io/sebadob/rauthy:0.18.1-20231106` / `ghcr.io/sebadob/rauthy:0.18.1-20231106-lite`

**Comment by anderspitman** [comment]
@damooo did you ever end up making a dpop client library for Rust? I see the dpop crate but after poking through the code a bit it's unclear to me whether it can be used for a client or if it's just type information.

**Comment by damooo** [comment]
@anderspitman
The `dpop` library should work.  It is type driven, follows [Parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) principle, in the sense, the codec, proof, validated-proof, payload, etc. all have their types, and corresponding methods and state transitions.

Also it provides typed headers for required dpop headers. Plz check the docs. Plz discuss at the repo, if you have any issues/questions.

**Comment by anderspitman** [comment]
@damooo I did look through the docs and it was very unclear how to actually use it. All I see is a bunch of types. That's great to hear that it should be functional though. Maybe it will make more sense after reading the article you linked, but even a couple basic examples would be very helpful. I'll post on the repo if I remain stuck, thanks.
