### ISSUE TITLE
Support social sign in

### ISSUE THREAD

**Issue by damooo** [sebadob/rauthy#166]
Signing in with google, github , etc, through oidc will be highly convinient for many service instances.

**Comment by sebadob** [comment]
This is something I thought about, that it may come, but this would be quite far into the future, because there are a lot of other things that are way more important ant this moment.
But yes, this is on the "it may come" TODO list already.

**Comment by erlend-sh** [comment]
Social sign-ins are less oppositional to Rauthy’s value proposition if you think of them strictly as an onboarding tool rather than a default method of sign in.

For a service like [Weird](https://blog.erlend.sh/weird-web-pages), we would like to use Rauthy to eventually become our own standalone OIDC provider to compete with the IdP incumbents (Google, GitHub et.al.) in our own small way.

But for first-time user registrations, it’d be a mistake to not support the “usual suspects” as a signup method, as that’s what the vast majority of people are used to, including on Weird’s competitors like linktree and biolink.

The proprietary login options could be challenged post-signup; in Weird’s case we’d wait maybe 2-3 months for the user to fully commit to our service, and then pop the question:

> “Do you want to upgrade your login with more security and privacy features? Switch to our Weird-ID for passkey login, MFA and zero tracking!”

**Comment by sebadob** [comment]
Yes, for an initial registration, it would be a nice feature, that's true. Just to grab some data that already exists.
At the moment, the benefit is not yet there, since you only can add your E-Mail and Name in the Account view, but this will change in the future.

If everything goes to plan, I will release v0.19.0 today with Solid OIDC support and some bugfixes.  
Adding more user values is planned for the release afterwards, most probably.

**Comment by sebadob** [comment]
Just as an update for this issue.

I have to do quite a bit of other work, before I can implement something like this.
The next (way more important) steps are to get fully compliant with the OIDC RFC.

Some smaller things are still missing for the mandatory party and I am thinking about making Rauthy compliant with the dynamic OIDC provider spec as well. This would however be a big one, since I would need to fully support the hybrid flow + implement dynamic client registration in a way, that the DB would not get filled by bots and spammers.

When this is done, I will most probably look at implementing upstream auth providers.

**Comment by Freyert** [comment]
Put another way is this: supporting [OIDC Connect discovery](https://openid.net/specs/openid-connect-discovery-1_0.html)?

**Comment by sebadob** [comment]
> Put another way is this: supporting [OIDC Connect discovery](https://openid.net/specs/openid-connect-discovery-1_0.html)?

This has nothing to do with this issue, but yes, Rauthy exports `/.well-known/openid-configuration` so clients can auto-configure themselves with just providing the issuer, which would be in the case of Rauthy something like `https://iam.example.com/auth/v1`.  
This would make the config available at  `https://iam.example.com/auth/v1/.well-known/openid-configuration`

**Comment by sebadob** [comment]
The first nightly version is available now for first tests in the real world.  
All the development and tests so far have been done against another Rauthy instance which acted as an upstream provider. Basically all OIDC providers (and I guess Oauth2 as well) should work now. The next step is to actually test it out against other real providers.  
I tried to reduce any validation as much as possible (while still stay safe) to achieve the highest amount of compatibility.

**Please do not use these nightly versions in a productive environment.**

If there are any problems which need modifications to the DB migrations, I will modify the migrations themselves instead of creating new ones to keep the whole thing clean. But if this is needed, you would get a conflict with the DB from this nightly version, because of a hash mismatch.

### SQLite 

```
docker run --rm -p 8080:8080 ghcr.io/sebadob/rauthy:0.22.0-240404-lite
```

### Postgres

```
docker run --rm -p 8080:8080 ghcr.io/sebadob/rauthy:0.22.0-240404
```

I added a first template for Google Accounts as well as a reference for future templates.  
I am pretty sure, that there will be some friction points left over to solve, but we only find these out when testing in the real world.

For the configuration, you can find a new nav entry `Providers` in the Admin UI.

![image](https://github.com/sebadob/rauthy/assets/62848396/303bbfaf-55b5-4d24-ac55-59c66da29149)

Please provide some feedback, when you have done testing, even when everything worked out fine.  
Thanks.

**Comment by sebadob** [comment]
There is a new nightly image available which has been tested and verified against Github as the upstream provider.

A detailed setup guide / docs will follow in the next days probably, but this is really simple.

### SQLite:
 ```
docker run --rm -p 8080:8080 ghcr.io/sebadob/rauthy:0.22.0-240408-lite
```

### Postgres:
 ```
docker run --rm -p 8080:8080 ghcr.io/sebadob/rauthy:0.22.0-240408
```

**Comment by sebadob** [comment]
Support has been added in [v0.22.0](https://github.com/sebadob/rauthy/releases/tag/v0.22.0)
