### ISSUE TITLE
Making rauthy pluggable

### ISSUE THREAD

**Issue by damooo** [sebadob/rauthy#174]
Currently `rauthy` can be deployed as standalone application, but is not trivial to plug into  an existing rust api, with custom configurations, mount point, etc.. as they all are globally dispersed and hardcoded.

If we can instantiate an `RAuthy` instance with custom config, and plug to [actix application's scope](https://actix.rs/docs/application#using-an-application-scope-to-compose-applications), it will be highly embeddale into any kind of rust app.

If open to idea, i could work on that.

**Comment by sebadob** [comment]
There are a few reasons why this would be a bad idea:

- The project in its current state has almost 50k lines of code
- Compilation already takes a huge amount of time as a standalone app
- The same reasons as already mentioned in https://github.com/sebadob/rauthy/issues/170
- If Rauthy should be "generic", because just everyone these days wants everything to be generic, it would not only bump up the complexity an insane amount, but it would also drastically reduce the efficiency and performance, because you need to resolve so much stuff at runtime, that I would never even think about doing something like this.
- There is just not a single good reason why you would want to do this. If you just want "some authentication" for an arbitrary application, which should be built-in, then you can do this with a few hundred lines of code (see reason No 1)
- Making this work properly would mean days of work, a way harder to maintain project and way more restricted possibilities in the future

There is one thing that would make sense, and that is something like a `rauthy-connector`. Basically a stripped down OIDC client that only provides the best and safest options for authentication that Rauthy supports. This would be a small independant crate with most probably under 1k lines of code in the end.

**Comment by sebadob** [comment]
Btw the `rauthy-connector` or however it will be called is already plannes for the near future, since I need this for the [nioca-client](https://github.com/sebadob/nioca-client) anyway.

**Comment by damooo** [comment]
> Compilation already takes a huge amount of time as a standalone app

Would make sure, it will not increase.

> If Rauthy should be "generic", because just everyone these days wants everything to be generic, it would not only bump up the complexity by an insane amount, but it would also drastically reduce the efficiency and performance, because you need to resolve so much stuff at runtime, that I would never even think about doing something like this.

Will make sure no performance degradation will be there. Only "modularization", not ultra genericization.

> Making this work properly would mean days of work, a way harder to maintain project and way more restricted possibilities in the future

Will try to be with in a week. And code to only be more maintainable.

This will enable the applications to have more control over the part, and they can react on events like user registration, etc to run custom logics, (like provisioning a pod), and much more.

**Comment by sebadob** [comment]
> Would make sure, it will not increase.

I mean it would increase the time for the app that adds Rauthy.

> Will make sure no performance degradation will be there. Only "modularization", not ultra genericization.

This would be unavoidable. The whole UI part is pre-compiled into static HTML as already mentioned in the other issue.

> This will enable the applications to have more control over the part, and they can react on events like user registration, etc to run custom logics, (like provisioning a pod), and much more.

You can already do this easily. Just create an API Key with Read access to events and listen to the stream.


In the end, I don't see any good reason why anyone should do this.

**Comment by damooo** [comment]
For example, this is what one can do with keycloak easily, to [embed](https://www.baeldung.com/keycloak-embedded-in-spring-boot-app). Being modular, and composable only bring clarity to code, and enable multitudes of usages.

In [Manas](https://github.com/manomayam/manas) (which is also 70k LOC), we want to embed rauthy, so that we can provide one binary dev environment for solid app developers.

**Comment by damooo** [comment]
@sebadob , can i start work on this?

**Comment by sebadob** [comment]
Keycloak has ~1k contributors and is backed by RedHat. It is a cool project, but what I don't like about it is the heavy weight and that they often break things between releases.

Maintaining a crate properly involves a lot more stuff than a standalone application and I will not do something half-baked. Rauthy does not want to be "just another Keycloak". The idea behind it is being an efficient and fast OIDC provider that just does, what it should and needs to do, and nothing else.

Until now, the only reason I see for something like that is that some other developers may start 1 docker container instead of 2 for their local dev env. That's not worth the huge overhead by any means.
