### ISSUE TITLE
Issue with /.well-known/openid-configuration: 404 Not Found

### ISSUE THREAD

**Issue by tobru** [sebadob/rauthy#259]
I'm trying to configure Forgejo to log in with rauthy, but I can't get the "OpenID Connect Auto Discovery URL" to work. To my understanding, the URL would be:

`https://id.example.com/.well-known/openid-configuration`

`id.example.com` is the domain where rauthy is running and working properly so far, but `/.well-known/openid-configuration` returns a 404 not found.

Am I doing something wrong?

**Comment by sebadob** [comment]
Hey

You are halfway there.  
But the well-known is not linked to the base URL, but to the Issuer instead.

The issuer when using Rauthy is not on `/` but `/auth/v1`.
Everything that Rauthy provides is using the `/auth` prefix, and then the API version (currently only v1 available).
The reason is, that this makes it really easy to integrate Rauthy with other applications using the same domain. As long as no other application uses `/auth` prefix, you can just uintegrate multiple apps easily behind a reverse proxy.

Meaning, in your case the issuer would be 
```
https://id.example.com/auth/v1
```

Usually, you only have to provide the correct issuer and the client will find the well-known by itself.

**Comment by tobru** [comment]
Thank you so much for the explanation, that helped a lot.
