### ISSUE TITLE
Do not force MFA for admin accounts

### ISSUE THREAD

**Issue by idc77** [sebadob/rauthy#292]
I wanted to give this a try, but now I have to add a MFA provider for my local test instance.

Don't assume to know better than anyone and tell people how to use ~~your~~ their software.
Also, what's wrong with just admin@localhost, why does it have to be localhost.de ?
admin@localhost is a perfectly valid email address, even a@a is.

For me, this forced MFA is a reason to not use this software.

**Comment by sebadob** [comment]
> I wanted to give this a try, but now I have to add a MFA provider for my local test instance.

Just take a look at the config:

```
#####################################
################ MFA ################
#####################################

# If 'true', MFA for an account must be enabled to access the
# rauthy admin UI (default: true)
#ADMIN_FORCE_MFA=true
```

> Don't assume to know better than anyone and tell people how to use your their software.

I simply don't. That's why you can configure everything. Rauthy just uses safe defaults and this will not change.

> Also, what's wrong with just admin@localhost, why does it have to be localhost.de ?
admin@localhost is a perfectly valid email address, even a@a is.

Rauthy is pre v1.0.0 and this is because of validation on the UI input form. Nothing is set in stone here and you can change this in seconds. You should never keep the default admin account when going into production anyway, never.

> For me, this forced MFA is a reason to not use this software.

Tbh, I don't care. If you don't like it, just don't use it, totally fine for me.  

You could have taken a look at the config and just disable MFA, you are not forced to do anything. Just disable it and if you don't like this software, then just don't use it. You could have asked for help, but instead of reading the config you posted this totally useless comment just complaining.

Closing this issue because it is already implemented long time ago.
