### ISSUE TITLE
The user is "stuck in the dashboard" after completing the registration

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#318]
The current flow is that a user can register an account, after register their account the user needs to verify there account. After clicking the verification/password reset the user gets redirected to the `rauthy user dashboard/control center`, which is a little bit confusing for the user. Speaken form a shop system it's disturbing that a user gets not back redirected to the shop and is "stuck in the rauthy dashboard". A configuration for a `post_redirect_uri` would be awesome! :heart:

**Comment by sebadob** [comment]
Okay, got it, with a CSR client, this cannot be done of course, yes.  

Regarding the pow, you don't need to re-implement that. I have published it: https://github.com/sebadob/spow

The `post_register_uri` doesn't really work. The registration is not bound to any client and there is no reference to a client while doing that. I don't get it where you would want to provide this query param.

**Comment by sebadob** [comment]
btw, my [leptos-captcha](https://github.com/sebadob/leptos-captcha) uses the exact same algorithm, you could copy & paste most of the code (since I know your FE is leptos :) ).

**Comment by kerkmann** [comment]
> Okay, got it, with a CSR client, this cannot be done of course, yes.

That is our main problem, more or less. ^^"

> The post_register_uri doesn't really work. The registration is not bound to any client and there is no reference to a client while doing that. I don't get it where you would want to provide this query param.

Oh! I see, I forgot that it's not bound to a client. Then the only solution would be a global setting (like I said, optional for backwards compatibility).

**Comment by sebadob** [comment]
After #321 you can actually do this dynamically.

The only thing you need to do is to have a custom link on your clients page to the registration form, if you don't want to implement the PoW yourself. You then can re-use Rauthy's "super pretty" registration form and provide a `recirect_uri` query param. This will be stored in the backend and after a successful password reset, the user will be redirected to the URI given during registration:

![2024-04-15_14-45](https://github.com/sebadob/rauthy/assets/62848396/91964084-0fb1-4153-8b4a-2f9de6de3c03)

**Comment by sebadob** [comment]
>  that is attached to the registration mail 

That would have been a bit unsafe, because if someone would be able to manipulate this URL, the user could be redirected to a malicious page. The state is not saved in the DB, which makes the whole thing safe.

**Comment by kerkmann** [comment]
@sebadob Thanks! You are awesome! :heart:

**Comment by sebadob** [comment]
I don't really see much security impact with this feature tbh.

You can add any `redirect_uri`, that's true. But you would be redirected to `evil.com` without any any login or token being exchanged. If you would end up in such a scenario, `evil.com` would need to trigger a new proper login flow for `evil.com` with everything you would need to do for any other client. It is the same as redirecting from `evil.com` to `google.com`s registration.

In the end, if the user allows `evil.com` to do a login, yes you could end up sending a token set (which is only valid for `evil.com` as well) to `evil.com` after the completion, but that is the case for any other single client, indenpendant from any registration happening before. `evil.com` would need to be a registered client at that point as well.

<hr>

But, I get what you mean. It is absolutely possible to lock this down further.

The checks for the registration endpoint, which are currently in place, are in the following order:

- check if `OPEN_USER_REG=true`
- check the email against `USER_REG_DOMAIN_RESTRICTION`
- check the email against `USER_REG_DOMAIN_BLACKLIST`

However, these are not related to the `redirect_uri`, if the registration is open.

If you want to restrict this further, my idea is pretty simple.

I will add another config var that can be set (or is probably set by default), that will compare the given `redirect_uri` against all `client_uri`s from registered clients, if they start the same way (because a callback could end up on a sub-domain with further actions). This would make it impossible to use this feature with Rauthy's ephemeral clients, but you can opt-out at any time. 

I guess this would solve your concerns @morki ?

**Comment by sebadob** [comment]
@morki done:

```
# If set to `true`, any validation of the `redirect_uri` provided during
# a user registration will be disabled.
# Clients can use this feature to redirect the user back to their application
# after a successful registration, so instead of ending up in the user
# dashboard, they come back to the client app that initiated the registration.
#
# The given `redirect_uri` will be compared against all registered
# `client_uri`s and will throw an error, if there is no match. However,
# this check will prevent ephemeral clients from using this feature. Only
# if you need it in combination with ephemeral clients, you should
# set this option to `true`. Otherwise it is advised to set the correct
# Client URI in the admin UI. The `redirect_uri` will be allowed if it starts
# with any registered `client_uri`.
#
# default: false
#USER_REG_OPEN_REDIRECT=true
```
