### ISSUE TITLE
Add template ability for the emails

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#319]
A configurable template (outside form the source code, on runtime level) for the emails would be awesome! :heart:

**Comment by sebadob** [comment]
This is a thing I though about, but not too easily accomplished. I mean, yes it would be easy, but it would have drawbacks as well. You would not get compile time checked templates and the generation / inserting of values would be a lot slower and require more resources by a huge margin, when this should be resolved dynamically.

For now, if you need custom templates, it would be very easy to do so with compiling it from source after modifying the templates.

I have to think about this, if / how this could be implemented.

**Comment by kerkmann** [comment]
A good approach would be to mount a template folder and use a template engine (like thymeleaf (just an example, there are better solutions out there)). Forking and compiling is on my opinion just a temporary solution, because you get quite easily out of sync with the origin. ^^"

**Comment by sebadob** [comment]
Yes of course you could mount a config map for instance for your kubernetes pod, but this comes with an overhead and would fully remove the "everything is inside a single binary" solution. The templates are baked into the binary for maximum efficiency and ease of use. The current templating engine is askama.

To get rid of the forking and out of sync issue, we could also add a just recipe like "build-with-templates" which will look for a custom templates folder. This would mean you don't have do modify any of the code.

There are quite a few solutions to this. I need to think about the best approach, because I don't really want to get rid of "everything is inside this single binary".

**Comment by sebadob** [comment]
I had a quick look into the templates.

When you want to customize them, do you mean the text content or "everything", like the whole HTML email incl CSS and so on? Because if its just about the text, this would actually be pretty easy to implement. We could simply read some String's at startup and inject them instead of reading the whole template.  
This would not come with any performance and efficiency drawbacks, if its just about the text itself.

**Comment by sebadob** [comment]
You can now do:

```
#####################################
############ TEMPLATES ##############
#####################################

# You can overwrite some default email templating values here.
# If you want to modify the basic templates themselves, this is
# currently only possible with a custom build from source.
# The content however can mostly be set here.
# If the below values are not set, the default will be taken.

# New Password E-Mail
#TPL_EN_PASSWORD_NEW_SUBJECT="New Password"
#TPL_EN_PASSWORD_NEW_HEADER="New password for"
#TPL_EN_PASSWORD_NEW_TEXT=""
#TPL_EN_PASSWORD_NEW_CLICK_LINK="Click the link below to get forwarded to the password form."
#TPL_EN_PASSWORD_NEW_VALIDITY="This link is only valid for a short period of time for security reasons."
#TPL_EN_PASSWORD_NEW_EXPIRES="Link expires:"
#TPL_EN_PASSWORD_NEW_BUTTON="Set Password"
#TPL_EN_PASSWORD_NEW_FOOTER=""

#TPL_DE_PASSWORD_NEW_SUBJECT="Passwort Reset angefordert"
#TPL_DE_PASSWORD_NEW_HEADER="Passwort Reset angefordert für"
#TPL_DE_PASSWORD_NEW_TEXT=""
#TPL_DE_PASSWORD_NEW_CLICK_LINK="Klicken Sie auf den unten stehenden Link für den Passwort Reset."
#TPL_DE_PASSWORD_NEW_VALIDITY="Dieser Link ist aus Sicherheitsgründen nur für kurze Zeit gültig."
#TPL_DE_PASSWORD_NEW_EXPIRES="Link gültig bis:"
#TPL_DE_PASSWORD_NEW_BUTTON="Passwort Setzen"
#TPL_DE_PASSWORD_NEW_FOOTER=""

# Password Reset E-Mail
#TPL_EN_RESET_SUBJECT="Neues Passwort"
#TPL_EN_RESET_HEADER="Neues Passwort für"
#TPL_EN_RESET_TEXT=""
#TPL_EN_RESET_CLICK_LINK="Klicken Sie auf den unten stehenden Link um ein neues Passwort zu setzen."
#TPL_EN_RESET_VALIDITY="This link is only valid for a short period of time for security reasons."
#TPL_EN_RESET_EXPIRES="Link expires:"
#TPL_EN_RESET_BUTTON="Reset Password"
#TPL_EN_RESET_FOOTER=""

#TPL_DE_RESET_SUBJECT="Passwort Reset angefordert"
#TPL_DE_RESET_HEADER="Passwort Reset angefordert für"
#TPL_DE_RESET_TEXT=""
#TPL_DE_RESET_CLICK_LINK="Klicken Sie auf den unten stehenden Link für den Passwort Reset."
#TPL_DE_RESET_VALIDITY="Dieser Link ist aus Sicherheitsgründen nur für kurze Zeit gültig."
#TPL_DE_RESET_EXPIRES="Link gültig bis:"
#TPL_DE_RESET_BUTTON="Passwort Zurücksetzen"
#TPL_DE_RESET_FOOTER=""
```
