### ISSUE TITLE
Add the ability to add a `ALLOW_ORIGIN` for the `GET /auth/v1/pow` endpoint

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#335]
Right now the `GET /auth/v1/pow` endpoint is only usable (with CORS) within the web ui. We would love to get a pow challenge without disabling CORS in the client. This would add the opportunity to create a custom frontend for user registration, just fetching a pow challenge, solve that challenge and create a `POST /auth/v1/users/register` for the registration. :)

Solution 1: Add a global `ALLOW_ORIGIN` config entry, which will be used for all that endpoints (`GET /auth/v1/pow`, `POST /auth/v1/users/register`).

Solution 2 (my personal preferred solution): Adding a `client_id` to the `query` could help to set the `ALLOW_ORIGIN` for the client. So this would mean that a `pow challenge` could be obtained by a `GET /auth/v1/pow?client_id=test` and their `ALLOW_ORIGIN` entry from that specific client.

Note: I am not sure about the `POST /auth/v1/users/register` endpoint, but I think the frontend would have the same issue there as well and would ran into some CORS issues (maybe adding a client there as well?). ^^"

**Comment by sebadob** [comment]
Yes that makes sense of course. Without it you would not be able to do remote user registration.

There a some tricky details though in the PoW validation and certains types do check for an existing session as well.
Let me check this.

**Comment by sebadob** [comment]
Could you please test with #336 ?

As I was looking at it, I changed from `GET` to `POST` for getting a PoW, because the get PoW actually creates the data and modifies the backend state, even though it is only inside the cache. Since a `GET` should never do that, I changed the endpoint to a `POST`.

I also simply allowed al origins for these 2 endpoints. There is no security issue with this. The PoW endpoint simply creates an in-memory data structe you can nothing do with on its own. The user registration endpoint checks anyway already, if the registration should be open. So if this is not the case, you would never get to the allow all origins header anyway.
Allowing it from everywhere is basically the definition of an open user registration. :)
