### ISSUE TITLE
When IP addresses are getting blacklisted, it's not showing in the `blacklist` page

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#352]
I can see a lot of events that some random/phishing IP addresses are getting blacklIst from rauthy (which is good), but none of them are shown in the `blacklist` tab. Is this intendeded? :)

**Comment by sebadob** [comment]
Of course you see them. You probably simply looked too late.  

The first blacklists are very short, actually the first one after 7 failed logins is 60 seconds to not totally lock out regular users that simply forgot their password. The auto-blacklisting time increases with the amount of failed logins.

**Comment by sebadob** [comment]
Just something else on that topic:

If you restart your application, you loose all the blacklisted IP's.  
Blacklistings are in-memory only and not persisted into the DB, because when you deal with blacklisting, the reason is usually spam / DoS and you want to do as little work and waste as little resources as possible not not get overwhelmed while being as fast as possible with rejecting such requests.

**Comment by kerkmann** [comment]
Okay thanks for the clarificaton, the event message:
```
2024/04/22 01:23:38
IpBlacklisted
xxx.xxx.xxx.xxx
2024/04/22 01:24:38
```
Was a little bit misleading, I haven't understand that the latest timestamp is the `blacklist until` timestamp. Maybe some potential for clarifications (in the future). :D

This issue can then be closed from my site, thanks! :heart:

**Comment by sebadob** [comment]
Yes these messages could be improved upon, or maybe documented in general.

Also, the Timestamp in these is always `UTC`
