### ISSUE TITLE
Upstream OIDC with LastLogin doesn't work for some IDs

### ISSUE THREAD

**Issue by anderspitman** [sebadob/rauthy#458]
Configuring upstream OIDC was very straight-forward. However, I noticed that one of my email addresses didn't work, resulting in

`Uncovered HTTP return status '400'. This should never happen, please report this bug.`

The email address contains a "&" character, which is valid in email addresses. My best guess is the validator didn't like that.

**Comment by sebadob** [comment]
Tbh I am not sure which characters exactly the regex is matching against. I am using the built-in email validation from the `validator` crate.

I this bug consistently reproducable with the `&` email address or does it happen just sometimes? Because I experienced some cache errors with old requests in the past but a some point was not able to reproduce them. They resulsted in such an error.

**Comment by sebadob** [comment]
Just so I can do a proper test and add it to the code base, was it something like `e&mail@example.com` ?

**Comment by sebadob** [comment]
The `&` in email validation is accepted like it should, the reason must be something else. Please check the logs from Rauthy to get more information. You may set `LOG_LEVEL=debug` to get detailed logging for the auth provider callback.

**Comment by sebadob** [comment]
Without additional information like debug logs or a way to reproduce it, I can't do anything about this or help you with it though.

**Comment by anderspitman** [comment]
Sorry for the ambiguous thumbs up! Was on mobile. I'm planning to try again with the logging and see if I can get a better errors message for you.

**Comment by sebadob** [comment]
`v0.23.3` should show the detailed error message now, if you get into that situation again.  
It simply shows the JSON deserialized error from the backend as is in the UI, which should help debugging.

**Comment by anderspitman** [comment]
Here's what the UI is showing now
![DeepinScreenshot_select-area_20240611061226](https://github.com/sebadob/rauthy/assets/7820200/e4f08d11-1513-45e4-bb35-7e843b797bcd)

**Comment by anderspitman** [comment]
I checked the network logs and found this under Respone:

```json
{
  "timestamp": 1718108103,
  "error": "BadRequest",
  "message": "Payload deserialization error: Error(\"invalid type: string \\\"test&@apitman.com\\\", expected a borrowed string\", line: 1, column: 65)"
}
```

**Comment by anderspitman** [comment]
It's possible that LastLogin is supposed to be doing some sort of encoding before putting that into the ID token. I'm not sure.

**Comment by sebadob** [comment]
> Here's what the UI is showing now (...)

Oh yeah, my bad... I love Javascript.. should have converted the body to string.

> I checked the network logs and found this under Respone:

The error is expected, since `test&@apitman.com` is an invalid email address. the `&` can't be directly in front of the `@`.
If it would be in the middle of the username part, it would be fine.

**Comment by sebadob** [comment]
As I am thinking about it, it seems that it complains about not receiving a string in the first place there. I actually created a test payload with `&` in email adresses and everything was fine, all tests passed. So it must be something with the payload itself.

**Comment by anderspitman** [comment]
> The error is expected, since `test&@apitman.com` is an invalid email address. the `&` can't be directly in front of the `@`. If it would be in the middle of the username part, it would be fine.

Do you have a link to the grammar you're using? A quick search didn't yield anything on this rule. FWIW gmail and outlook both work fine sending to that address.

> As I am thinking about it, it seems that it complains about not receiving a string in the first place there. I actually created a test payload with & in email adresses and everything was fine, all tests passed. So it must be something with the payload itself.

Happy to help with further debugging if I can. It's certainly possible I'm returning bad data.

**Comment by anderspitman** [comment]
I mean is this proper behavior? Maybe the lib I'm using is supposed to be using utf8. I'm not sure what the spec says about that. It's also possible I can control this from my code using a raw string or something.

**Comment by sebadob** [comment]
I am not sure, if this is correct. Usually you would never notice this, because all `String` conversions in all languages usually automatically convert such things. I only stumbled about this, because I did not do this on purpose to get rid of unnecessary memory allocations. Since this does not do anything with the data and therefore no automatic conversions under the hood, it created this error.

When I take a quick look at the [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-7.1) for JWT Tokens, in *7.1 Creating a JWT* I find this:

```
   2.  Let the Message be the octets of the UTF-8 representation of the
       JWT Claims Set
```

Rust Strings are UTF8 always, so this side should be correct. If the `\u0026` in this case is allowed, I am just not sure.
Also, even though it works with other clients / IdPs, it does not necessarily mean, that this is correct.  If I would use the easy way and just deserialized into owned `String`s, I would never get into that situation.
Even when I import your example token above into the Rust code and use default `String`s, I don't get any errors.
Only when I use types that do not do any auto-conversion, I notice the problem.

So, I really don't know for sure. From reading the RFC, I would assume that it's not correct, but I might be wrong on this.
I just leave the fix implemented. Luckliy it is not the end of the World. I am using `Cow<'a, str>` now, which is a thin wrapper around the data and only creates an owned `String` if necessary.
