### ISSUE TITLE
A few UI suggestions

### ISSUE THREAD

**Issue by anderspitman** [sebadob/rauthy#466]
* All the text inputs have autocomplete off. At least for debugging it's annoying to have to retype everything
* Indicate which fields are required. As an example, Providers>Add New>Submit hangs unless I specify both a Client Name and Client ID.

**Comment by sebadob** [comment]
Thanks, yes a complete look over the UI is one of the last big TODOs on the list before v1.0.0. 
The `autocomplete=off` will not change however, because debugging is not the use case, it is production use and if I have inputs without automcomplete, you can get very weird suggestions from browsers which do not make any sense at all.  

The UI should not hang in that case, I just saw it myself as well. It should reject the submit like it does in all other places.
This is limited to the provider ad new however. In all other places you see an error message for required fields.

**Comment by anderspitman** [comment]
> The autocomplete=off will not change however, because debugging is not the use case, it is production use and if I have inputs without automcomplete, you can get very weird suggestions from browsers which do not make any sense at all.

Do you have specific examples of what you've run into? Generally I find the suggestions reasonable, at least for text inputs that have a specific type. This is especially useful for `<input type='email'>` and `<input type='url'>`

**Comment by sebadob** [comment]
Inputs with a specific type should have auto completion turned on. If not, this is not intended. 
All "generic" inputs should have it turned off, because browsers suggest everything they know when I tested this in the past. But I haven't in a long time. These were created years ago by now.

I will check on this again.

**Comment by anderspitman** [comment]
Providers>Add New>Issuer URL doesn't have the url type, and thus no autocomplete. Strangely, the admin email input does have autocomplete set, but it doesn't work for me.
![DeepinScreenshot_select-area_20240611075603](https://github.com/sebadob/rauthy/assets/7820200/92722c25-7f7c-4f48-9c5e-f1b347fc58ca)

**Comment by sebadob** [comment]
Yes, I will have another look at this.  

Currently, all the UI work is a bit on hold. I am doing tests and building some components offline and I am evaluating Leptos for the Rauthy UI. I would like to have the project 100% Rust for ease of use and maintainability. The current setup with Svelte and static HTML works fine and is super efficient, but a bit hard to get into for new developers. So, all of these issues might resolve automatically in the future.
