### ISSUE TITLE
Question about todo:  UI overhaul to make it "prettier" in certain places

### ISSUE THREAD

**Issue by ellieschieder** [sebadob/rauthy#517]
Hey,
Wanted to ask what places you mean in particular /o\

**Comment by ellieschieder** [comment]
The documentation thing - Yeah noticed that.

Leptos - Will look into it :D (as in look into it in general)

**Comment by ellieschieder** [comment]
Also -> Thanks. rauthy is nearly 100% what I need for some projects. As soon as I'm able too, I will sponsor you. 

One thing Im still not getting however is OIDC dynamic client registration.... :D

**Comment by sebadob** [comment]
Thank you!

Rauthy is by now nearly 100% where I wanted it to be. ^^

Just the UI part, get a nicer logo and some smaller stuff. And maybe, as I am working on a new project right now, add support to run it with an embedded SQLite, but replicated with Raft, because Postgres connections are pretty costly in terms of memory and after testing, SQLite can handle everything with ease, at least this type of application.

Regarding DCR, I mentioned it pretty high level in the latest docs for [Ephemeral Clients](https://sebadob.github.io/rauthy/work/ephemeral_clients.html#ephemeral-clients). A dedicated DCR doc does not exist, but i would not make much sense probably because Rauthy is just following the official OIDC spec in this case.  
But, the support is mostly only there for existing applications and from my experience, it is rarely used, because it is a pretty big burden on the client side. The client apps need to manage themselves. The ephemeral clients are much easier to handle and to maintain, if you need any kind of dynamic client config, but at the cost that their config is "public", when you know where to look, if this is a concern for you.

**Comment by sebadob** [comment]
I guess the question is answered, right? I would close the issue then.
