### ISSUE TITLE
Configuration via environment variables

### ISSUE THREAD

**Issue by ellieschieder** [sebadob/rauthy#518]
Is it currently possible to configure rauthy completely or partial via environment variables (e.g. docker compose)?

If not, what / where would changes need to be made?

**Comment by sebadob** [comment]
Yes, absolutely.

This is the reason why the config variables have such long names sometimes, because they are not organized in a `toml` file. You can choose whatever you like more, either env vars or provide a config file.

If you provide both, the config file will be parsed first and the env vars will have the higher priority.

**Comment by ellieschieder** [comment]
Awesome! Do I need to prefix the env variables?

**Comment by sebadob** [comment]
No, just use the exact same names. 

The way Rauthy does it is it's parsing the optionally given config file as raw env variables. This is why they must not contain whitespace around `=` for instance, but in the end makes the configuration a lot more flexible. For instance, for testing some stuff, I can just edit env vars on the fly which is much fast in docker or kubernetes than modifying a ConfigMap.
