### ISSUE TITLE
Possibility to use JWE as an alternative to JWT for OIDC tokens(id, access, dpop & refresh)

### ISSUE THREAD

**Issue by JorgeReus** [sebadob/rauthy#556]
Hello there!

This is a request to support JWE in rauthy

I'm in love with rauthy so far, I wonder if it would be possible to encrypt all the JWTs from the OIDC exchange following the [JWT](https://datatracker.ietf.org/doc/html/rfc7516) RFC. AFAIK Generating the tokens are half of the picture since some providers support JWT can in the upstream providers feature, the returned tokens will be encrypted.

Thanks beforehand!

**Comment by sebadob** [comment]
JWE is not an alternative to JWT. It can be used to encrypt the payload of a JWT.  

JWT Tokens can be used in lots of situations. JWE makes sense in scenarios, when you use a JWT for instance as a license for a software or other things like that.

Rauthy does not support JWT payload encryption, because it does not make any sense in this context, imho.  
When you have a token from Rauthy, no matter if the payload would be encrypted or not, you could simply use it on the `/userinfo` endpoint to get all the information inside anyway. This means payload encryption (in this case) is an overhead with many downsides and without any benefit.
