### ISSUE TITLE
Feat: Possibility of Routing to Company IdP Based on Email/Company Name and Group-Specific API Tokens

### ISSUE THREAD

**Issue by KaanMol** [sebadob/rauthy#588]
Hi!

I want to start by saying how much I appreciate your work on Rauthy! It's a fantastic project, and I have a feature request that I’m curious about.

Would it be possible to implement functionality where, based on the user's email or company name, they could be routed to their organization's Identity Provider (IdP)? I’m envisioning something similar to how providers like Okta handle this. Whether this is done through a single login screen, an API, or some other approach, I’m interested in your thoughts on whether this functionality could be added.

I noticed Rauthy supports grouping, but I’m not sure if that would be suitable for organizations or if there’s a more appropriate solution for this use case.

Additionally, would it be possible to generate API tokens specific to a group or organization? This would allow me to hand out tokens to specific groups so they can interact with my API.

If this sounds like a useful feature for Rauthy, I’d be happy to contribute to its development. Let me know if it’s something you’d consider or if you have any recommendations for achieving this functionality.

Thanks again for all your hard work on Rauthy. Looking forward to hearing your feedback!

**Comment by sebadob** [comment]
> I want to start by saying how much I appreciate your work on Rauthy! It's a fantastic project, and I have a feature request that I’m curious about.

Thanks a lot!

> Would it be possible to implement functionality where, based on the user's email or company name, they could be routed to their organization's Identity Provider (IdP)? I’m envisioning something similar to how providers like Okta handle this. Whether this is done through a single login screen, an API, or some other approach, I’m interested in your thoughts on whether this functionality could be added.

I don't really get what you want to achieve. When you just want to redirect users to other IdPs, what do you want Rauthy for in the first place, when it should only redirect and don't do anything else?

I guess dividing the deployment into multiple companies resembles to what Realms in Keycloak are. I decidided to intentionally not include this additional abstraction layer into Rauthy to not overload it with stuff that you don't need most of the time. Rauthy is so efficient, that the idea in such a case is, that you just deploy multiple instances, which makes the whole thing a lot simpler. 

Multiple deployments show a clear separation between companies even for someone that doesn't know anything about it, because you could directly see it when looking at the deployment name, namespace, or however you separate instances.
You also get dedicated admin UI branding matching each company.

> Additionally, would it be possible to generate API tokens specific to a group or organization? This would allow me to hand out tokens to specific groups so they can interact with my API.

This is solved automatically as well if you just have multiple deployments. Another bonus probably is, if you don't unify all of them in a single place where you could mess up something with a bad configuration (because we're all just human), it is also more secure out of the box.

**Comment by KaanMol** [comment]
Well, it is the same idea as the Social Providers like GitHub, the difference would be that when you enter an email it gets triggered, instead of clicking on the button "Login with GitHub" or something. Maybe I explained it a bit wrong. Rauthy would still give the options to have a second factor etc.

It could even be a button as "Login with SSO" and after that you have to fill in a company name or your email before the right login screen can be given etc

**Comment by KaanMol** [comment]
> Ahh okay, got it. So you would like an option that basically forces a user, depending on the E-Mail domain, to a specific IdP, which would at the same time make it impossible to use Rauthy directly, even if the account will exist after the first login anyway?
The company itself would set those settings basically.

What I want to do on my end (this doesnt have to be fully in Rauthy), they create an organization, specify that members of their company can login, also provide the details of the provider etc. Employees or other users can then login and directly get assigned the right roles etc. 

Honestly, what I try to achieve is maybe not something in the scope of Rauthy, it would be something like Clerk, Auth0, Okta etc. Github also has a [similar setup](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authenticating-with-a-managed-user-account#authenticating-via-the-login-page). I rather have it on one server instead of multiple deployments.  But I would totally understand if it too much of an overhaul
