### ISSUE TITLE
[ADFS] rfc6749 The client MUST NOT use more than one authentication method in each request.

### ISSUE THREAD

**Issue by cocoon** [sebadob/rauthy#658]
Hi,
I had my first days with using rauthy and wanted to add Microsoft ADFS (Windows Server 2019) as OIDC Provider and got it nearly working after some problems.

At the very beginning I got the following error:
PeerIncompatible ServerTlsVersionIsDisabledByOurConfig
Windows 2019 has no support for TLS 1.3.
But I got it somehow working in the end with "Allow insecure TLS certificates" for now.
Will maybe try with Server 2025 later again.

Reverse-Proxies seem to be problematic for ADFS.
(https://peter.upfold.org.uk/blog/2016/05/31/reverse-proxying-adfs-with-nginx/)

But the final error now seems to be, that ADFS doesn't like to get "Multiple client authentication methods" in a request.

I found the same problem and hints here:
https://github.com/coreos/go-oidc/issues/181

> Keycloak was sending auth-code to exchange for access token at ADFS server's token endpoint, with both client-authentication methods: basic and post, which violates

and here:
https://github.com/FusionAuth/fusionauth-issues/issues/445

> The problem that is described by MSIS9631 is caused because we are sending the client_secret in the request body and as part of a Basic Authorization header.
> 
> We did this to support a few IdPs such as Discord that only accept the client_secret in the request body, even though the OIDC spec says that at a minimum you have to support HTTP Basic Authorization.
> 
> This is the first time I've seen an IdP puke because we send it both ways. To solve this and support other IdPs that require it to be one or the other, we'll have to expose some additional configuration to allow the IdP configuration to specify which mode to utilize, client_secret_basic or client_secret_post. [there seemed to be a typo in the original message]

From:
https://datatracker.ietf.org/doc/html/rfc6749#section-2.3

The client MUST NOT use more than one authentication method in each request.

Could that option (client_secret_basic or client_secret_post or both) be added here,too?

**Comment by sebadob** [comment]
> Windows 2019 has no support for TLS 1.3.

Even though I will add a limitation for TLS 1.2+ soon, at the moment, Rauthy does not limit the versions and all of them are allowed by default. Do you maybe use a reverse proxy for TLS termination which restircts the versions?

> The client MUST NOT use more than one authentication method in each request.

Rauthy does not do this. What it does, it checks for `Basic` auth first when you use a confidential client on `/token` and falls back the `client_id` and `client_secret` in the body, if the `Authorization` header does not exist. This was needed for compatibility in some situations back then.
At which point exactly do you get this error? On `/authorization` already, or when ADFS tries to fetch a token set from a received `code` ? The only place where Rauthy advertises these 2 methods is in the `openid-configuration` of course to let client's know it can do both.

**Comment by cocoon** [comment]
Yesterday I tested with Auth0 and that was working OK (just as feedback).

Did another test today with JumpCloud today and failed to get it working.
I expect that if there is an option to configure one explicitly like for ADFS it might also fix this provider.
The last error looks like a bug.


I have to select only one of the three options, cannot select multiple:
Client Secret Post
Client Secret Basic
Public (None PKCE)

I tried with all 3 and got the following errors:

**Client Secret Post**

`HTTP 500: {"timestamp":1734510840,"error":"Internal","message":"HTTP 401 during POST https://oauth.id.jumpcloud.com/oauth2/token for upstream auth provider 'XXX'\n{\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The OAuth 2.0 Client supports client authentication method 'client_secret_post', but method 'client_secret_basic' was requested. You must configure the OAuth 2.0 client's 'token_endpoint_auth_method' value to accept 'client_secret_basic'.\"}"}`

**Client Secret Basic**

`HTTP 500: {"timestamp":1734510848,"error":"Internal","message":"HTTP 401 during POST https://oauth.id.jumpcloud.com/oauth2/token for upstream auth provider 'XXX'\n{\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The OAuth 2.0 Client supports client authentication method 'client_secret_basic', but method 'client_secret_post' was requested. You must configure the OAuth 2.0 client's 'token_endpoint_auth_method' value to accept 'client_secret_post'.\"}"}`


**Public (None PKCE)**

`HTTP 400: {"timestamp":1734510551,"error":"BadRequest","message":"Payload deserialization error: Error(\"invalid type: string \\\"true\\\", expected a boolean\", line: 1, column: 156)"}`

**Comment by sebadob** [comment]
Oh yes the jumpcloud logs look buggy tbh.

If ADFS supports public client + S256 PKCE, that should work without any issues, because it does with Rauthy for many other clients.

That it complains about the client creds being present in the `Authorization` header as `Basic` and in the body does not make any sense from a security standpoint on though. What the RFC says about the MUST NOT use multiple methods is do not mix and match public and confidential clients, which makes a lot of sense.

The thing with Basic Auth + Body, as long as they contain the same information, is that any way is as secure as the others. These secrets could leak only if an attacker would be able to sniff the traffic in situations like unencrypted HTTP after a reverse proxy, or on an infected Firewall with DPI and such things. But then it does not matter at all, if they are in the header, in the body, or both. No other upstream IdP had any issues with that so far and I tested quite a few already.

Anyway, I will add an option to select them in the configuration, but don't know how fast this will come, because I just started a huge UI migration to Svelte 5. Maybe I can slip that in beforehand, need to have a look at this.

Edit:

> HTTP 400: {"timestamp":1734510551,"error":"BadRequest","message":"Payload deserialization error: Error(\"invalid type: string \\\"true\\\", expected a boolean\", line: 1, column: 156)"}

That one looks scary... that they send a `bool` as string.

**Comment by sebadob** [comment]
Please give `ghcr.io/sebadob/rauthy:0.27.3-20241218`, but don't use it with a production database. It applies a database migration and I might need to add something to that one before the next stable release, which would break the current one, if their hashes differ.

**Comment by cocoon** [comment]
oh wow thanks, that was quick! Will give it a try 👍

**Comment by sebadob** [comment]
Btw, I also reduced the min TLS version of the clients down to `TLS v1.2`, which should help with Windows Server 2019 as well.

**Comment by cocoon** [comment]
can it be that this change:

client_id: None,

https://github.com/sebadob/rauthy/commit/b81225ee6ad008092ad11c9d1669636f8a586838#diff-c56295d2c086fb62d24323c503554a3e1d0ecc509f46398e2fa8f9bd771065e8R918

breaks auth with PKCE when I disable client_secret_basic and client_secret_post?

As I now receive the following error:

`HTTP 500: {"timestamp":1734528849,"error":"Internal","message":"HTTP 400 during POST https://x.x.lab/adfs/oauth2/token/ for upstream auth provider 'XXX'\n{\"error\":\"invalid_request\",\"error_description\":\"MSIS9606: The \\u0027client_id\\u0027 parameter is not specified. The access token request must contain \\u0027client_id\\u0027 parameter for public clients.\"}"}`


Because when I enabled client_secret_basic with PKCE it worked in 2019 👍
Still had no success without PKCE, but still trying ...

btw I had a feeling that if a custom certificate was specified ones, I was not able to disable it again, if I can write down  reproducible steps, I can add it as new issue.

**Comment by sebadob** [comment]
> breaks auth with PKCE when I disable client_secret_basic and client_secret_post?

Oh, yes, that's true. The `client_id` in the body should be added all the time for public clients.
I will build a new nightly for testing.

But, does the confidential client work with the changes?

> btw I had a feeling that if a custom certificate was specified ones, I was not able to disable it again, if I can write down reproducible steps, I can add it as new issue.

I will have a look. Usually, if you just empty the input in the UI, it should be deleted.

**Comment by sebadob** [comment]
> btw I had a feeling that if a custom certificate was specified ones, I was not able to disable it again, if I can write down reproducible steps, I can add it as new issue.

That was actually true, didn't catch that yet. But it was only a validation error in the UI while it worked as expected in the backend.

**Comment by cocoon** [comment]
I got a step further with Jump Cloud using post or basic, but in the end it fails with:

`HTTP 400: {"timestamp":1734534044,"error":"BadRequest","message":"Payload deserialization error: Error(\"invalid type: string \\\"true\\\", expected a boolean\", line: 1, column: 156)"}`

And I think this may be the field "email_verified" that is set to true as soon as I enable the Email scope in Jump Cloud.
I cannot remove this static field.

If I disable the Email scope it complains that email is required.

Sadly I currently don't know where I could see the token as json where it comes from and how the value for email_verified looks like.

Regarding the UI:

- When adding a "custom" provider, there is 2 times the slider for "Allow insecure TLS certificates".
- When saving an automatic (maybe) one, it sometimes did not work and was saving forever ... showing 2 buttons with moving dots (will try to make a screenshot next time I get it happening)

**Comment by sebadob** [comment]
`ghcr.io/sebadob/rauthy:0.27.3-20241218-1` now always set's the `client_id` in the body for `/token` requests which should fix the PKCE issue with a public client.

It always makes it possible to remove a custom root PEM from a client via the UI.

**Comment by sebadob** [comment]
> Sadly I currently don't know where I could see the token as json where it comes from and how the value for email_verified looks like.

The error say's it already. The field is sent as `email_verified: "true"` while it should be `email_verified: true`, since it field must be a boolean, not a string. So that's actually a bug in jumpcloud. 
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

I could of course simply parse any JSON value, but that's handling the symptom of a wrong implementation, not the cause.

**Comment by cocoon** [comment]
> The error says it already

It says that "something" is returning true as a string, but not where or what exactly :)
I think I need a dev env, I don't like working blind ^^

"I could of course simply parse any JSON value, but that's handling the symptom of a wrong implementation, not the cause."
No, if I can make sure that it is that field, I will tell them. I just always think: "I cannot be the first one who has this problem, it must be my fault"

**Comment by sebadob** [comment]
> It says that "something" is returning true as a string, but not where or what exactly :)
I think I need a dev env, I don't like working blind ^^

Totally understand that, yes. But when you take a look at the [AuthProviderIdClaims](https://github.com/sebadob/rauthy/blob/abaf24036eec50d74431bc069994d532b56e7362/src/models/src/entity/auth_providers.rs#L1156), there is only one claim that is deserialized into a `bool`, and that is `email_verified`. I am almost 100% sure that the line throwing this error is [this one](https://github.com/sebadob/rauthy/blob/abaf24036eec50d74431bc069994d532b56e7362/src/models/src/entity/auth_providers.rs#L1174), which tries to deserialize the `id_token`. It also makes sense, that it throws this error as soon as you add `email` to the claims, because this only adds `email` and `email_verified`, while only `email_verified` is and must be a boolean.

Errors like these are actually pretty common when backends are written in languages like JS, which don't care that much. I've seen these many times already. Most probably it will deserialize just fine when you change 

```rust
email_verified: Option<bool>,
```

into 

```rust
email_verified: Option<serde_json::Value>,
```

for the `AuthProviderIdClaims`. The thing is, that Rauthy actually ignores this field, because it does not know, if the upstream IdP actually verified it or just sets it to true. I can quickly push an image for you, as I have free ressources on one machine.

> I just always think: "I cannot be the first one who has this problem, it must be my fault"

That's actually a good trait to have and I am like that too. It's way better than people complaining "this is broken" while it was clearly a user error.

**Comment by cocoon** [comment]
Nice service,thanks, will try it tomorrow 👍

**Comment by cocoon** [comment]
Tested JumpCloud and now it is working, so this proves it, thanks, I will contact them ^^

**Comment by cocoon** [comment]
Got already a response ... don't know if "for a while now" should tell me something about their speed for fixing things ... 

> Thank you for bringing this to our attention. I understand that you are experiencing an issue where the `email_verified` field in the ID token returned by JumpCloud is being sent as a string ("true"/"false") instead of a boolean (true/false). This behavior does not conform to the expected OIDC standard and is causing issues with applications that strictly adhere to the OIDC specification.
> 
> Our engineering team has been aware of this issue for a while now and has been actively working on a resolution. I have added your request to the ongoing task. 
> 
> Unfortunately, I do not have an estimated time for when this feature will be released.

**Comment by sebadob** [comment]
> Got already a response ... don't know if "for a while now" should tell me something about their speed for fixing things ...

That is really bad, since the fix is super tiny, wow. But at least everything else is working, so I will merge the changes into main, without the jumpcloud specifics.

Thanks for your testing.
